import type { PrivatePackageReleaseConfig, SbomAdmission } from "./config.mjs";
import type { ReleaseState } from "./state.mjs";

export type ReleaseAssetEvidence = { name: string; sha256: string };
export type ReleaseCandidate = {
  id: string;
  packageDirectory: string;
  generatedPaths: string[];
  sourcePaths: string[];
  admission: SbomAdmission;
  packageName: string;
  version: string;
  tagName: string;
  state: ReleaseState;
  latestMode: string;
  distTagsBefore: Record<string, string>;
  versionsBefore: string[];
  sourceSha: string;
  sourceEpoch: string;
  packageSourceSha256: string;
  licenseBlob: string;
  lockfileBlob: string;
  configBlob: string;
  workflowBlob: string;
  rootManifestBlob: string;
  workspaceBlob: string;
  npmrcBlob: string;
  releaseInputSha256: string;
  archiveName: string;
  archivePath: string;
  archiveSha256: string;
  releaseDirectory: string;
  sbomName: string;
  sbomPath: string;
  sbomSha256: string;
  sbomEvidence: Record<string, unknown> & { componentCount?: number };
  checksumName: string;
  checksumPath: string;
  checksumSha256: string;
  localAssets: ReleaseAssetEvidence[];
  existingReleaseAssets: string[];
  missingReleaseAssets: string[];
  releaseId: number | null;
  tagTargetSha: string | null;
};
export type ReleaseReceipt = {
  profile: string;
  sourceSha: string;
  releaseRoot: string;
  repository: string;
  registry: { url: string; scope: string };
  config: { path: string; gitBlob: string; sha256: string };
  verifier: Record<string, string>;
  packages: ReleaseCandidate[];
};
export function preparePrivatePackageRelease(input: {
  sourceSha: string;
  releaseRoot: string;
  verificationRoot: string;
  clients: unknown;
  config: PrivatePackageReleaseConfig;
  configEvidence: { gitBlob: string; sha256: string };
  verifier: Record<string, string>;
}): Promise<ReleaseReceipt>;
export function revalidatePrivatePackageRelease(input: {
  receipt: ReleaseReceipt;
  clients: unknown;
  config: PrivatePackageReleaseConfig;
}): Promise<void>;
export function publishPrivatePackageRelease(input: {
  receipt: ReleaseReceipt;
  clients: unknown;
  config: PrivatePackageReleaseConfig;
}): Promise<void>;
